/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    GeneratedStory: typeof import('./src/components/GeneratedStory.vue')['default']
    ImageCaptation: typeof import('./src/components/ImageCaptation.vue')['default']
    ImageDisplay: typeof import('./src/components/ImageDisplay.vue')['default']
    ImageSelect: typeof import('./src/components/ImageSelect.vue')['default']
    StoryCard: typeof import('./src/components/StoryCard.vue')['default']
    StoryTeller: typeof import('./src/components/StoryTeller.vue')['default']
  }
}
