###
POST http://127.0.0.1:8000/generate-by-url HTTP/1.1
content-type: application/json

{
    "image_url": "https://images.pexels.com/photos/19599971/pexels-photo-19599971/free-photo-of-an-old-man-standing-on-the-shore-near-a-pier.jpeg",
    "image_text_input": "a photograph of",
    "generate_options": {
        "max_new_tokens": 300,
        "temperature": 0.7,
        "do_sample": true
    }
}
###
POST http://127.0.0.1:8000/generate-by-url HTTP/1.1
content-type: application/json

{
    "image_url": "https://images.pexels.com/photos/14803768/pexels-photo-14803768.jpeg",
    "image_text_input": "a photograph of",
    "generate_options": {
        "max_new_tokens": 300,
        "temperature": 0.7,
        "do_sample": true
    }
}
###

POST http://127.0.0.1:8000/generate-by-url HTTP/1.1
content-type: application/json

{
    "image_url": "https://images.pexels.com/photos/19599971/pexels-photo-19599971/free-photo-of-an-old-man-standing-on-the-shore-near-a-pier.jpeg",
    "generate_options": {
        "max_new_tokens": 300,
        "num_beams": 5,
        "num_return_sequences": 5
    }
}
###
POST http://127.0.0.1:8000/generate-by-url HTTP/1.1
content-type: application/json

{
    "image_url": "https://images.pexels.com/photos/14803768/pexels-photo-14803768.jpeg",
    "generate_options": {
        "max_new_tokens": 300,
        "num_beams": 5,
        "num_return_sequences": 5
    }
}

###
POST http://127.0.0.1:8000/generate-by-file HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary1234567890

--boundary1234567890
Content-Disposition: form-data; name="file"; filename="free-photo-of-an-old-man-standing-on-the-shore-near-a-pier.jpeg"
Content-Type: image/jpeg

<@INCLUDE <path-to-image>>

--boundary1234567890
Content-Disposition: form-data; name="image_text_input"

a photograph of
--boundary1234567890
###
